from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from pydantic import ValidationError

from .explainer import explain_plan
from .hardware_parser import summarize_hardware
from .llm_explainer import explain_plan_with_optional_llm
from .models import CommandRisk, InstallPlan, SystemReport
from .openai_compatible import OpenAICompatibleClient, OpenAICompatibleClientError
from .planner import create_initial_plan


_RISK_ICON = {
    CommandRisk.SAFE: "[safe]",
    CommandRisk.MEDIUM: "[medium]",
    CommandRisk.HIGH: "[high]",
    CommandRisk.CRITICAL: "[critical]",
}


def _load_report(path: Path) -> SystemReport:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"Diagnostic report not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON report: {path}: {exc}") from exc

    try:
        return SystemReport.model_validate(raw)
    except ValidationError as exc:
        raise SystemExit(f"Report does not match SystemReport schema:\n{exc}") from exc


def _render_plan(plan: InstallPlan) -> str:
    lines: list[str] = []

    lines.append("# Arch Btrfs AI Advisor")
    lines.append("")
    lines.append("## Summary")
    lines.append(plan.summary)
    lines.append("")

    if plan.assumptions:
        lines.append("## Assumptions")
        for assumption in plan.assumptions:
            lines.append(f"- {assumption}")
        lines.append("")

    if plan.warnings:
        lines.append("## Warnings")
        for warning in plan.warnings:
            lines.append(f"- {warning}")
        lines.append("")

    lines.append("## Steps")
    for index, step in enumerate(plan.steps, start=1):
        lines.append(f"{index}. {step.title}")
        lines.append(f"   {step.description}")
        if step.command is not None:
            icon = _RISK_ICON[step.command.risk]
            confirm = "requires confirmation" if step.command.requires_confirmation else "no confirmation required"
            lines.append(f"   - Command: `{step.command.command}`")
            lines.append(f"   - Risk: {icon} {step.command.risk.value} ({confirm})")
            lines.append(f"   - Reason: {step.command.reason}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _has_critical_commands(plan: InstallPlan) -> bool:
    return any(
        step.command is not None and step.command.risk == CommandRisk.CRITICAL
        for step in plan.steps
    )


def _has_warnings(plan: InstallPlan) -> bool:
    return bool(plan.warnings)


def _write_or_print(content: str, output: Path | None) -> None:
    if output is None:
        print(content, end="")
        return

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")


def _build_llm_client(provider: str | None):
    if provider is None:
        return None

    if provider == "openai-compatible":
        try:
            return OpenAICompatibleClient.from_env()
        except OpenAICompatibleClientError as exc:
            raise SystemExit(str(exc)) from exc

    raise SystemExit(f"Unsupported LLM provider: {provider}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Create a conservative Arch Btrfs installation plan from diagnostics JSON."
    )
    parser.add_argument(
        "report",
        type=Path,
        help="Path to diagnostics/system_report.json generated by scripts/diagnostics.sh.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the generated InstallPlan as JSON instead of Markdown.",
    )
    parser.add_argument(
        "--explain",
        action="store_true",
        help="Print a human-readable explanation instead of the raw plan.",
    )
    parser.add_argument(
        "--llm-provider",
        choices=["openai-compatible"],
        help="Optional LLM provider used only with --explain. Requires provider-specific env vars.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Write the generated plan to a file instead of stdout.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Return exit code 2 when the plan contains warnings.",
    )
    parser.add_argument(
        "--fail-on-critical",
        action="store_true",
        help="Return exit code 3 when the plan contains critical commands.",
    )

    args = parser.parse_args(argv)

    if args.json and args.explain:
        raise SystemExit("--json and --explain cannot be used together")

    if args.llm_provider and not args.explain:
        raise SystemExit("--llm-provider requires --explain")

    report = _load_report(args.report)
    summary = summarize_hardware(report)
    plan = create_initial_plan(summary)

    if args.json:
        rendered = plan.model_dump_json(indent=2) + "\n"
    elif args.explain:
        client = _build_llm_client(args.llm_provider)
        if client is None:
            rendered = explain_plan(plan)
        else:
            rendered = explain_plan_with_optional_llm(plan, client=client).explanation
    else:
        rendered = _render_plan(plan)

    _write_or_print(rendered, args.output)

    if args.fail_on_critical and _has_critical_commands(plan):
        return 3

    if args.strict and _has_warnings(plan):
        return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
