from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from pydantic import ValidationError

from .hardware_parser import summarize_hardware
from .models import CommandRisk, InstallPlan, SystemReport
from .planner import create_initial_plan


_RISK_ICON = {
    CommandRisk.SAFE: "[safe]",
    CommandRisk.MEDIUM: "[medium]",
    CommandRisk.HIGH: "[high]",
    CommandRisk.CRITICAL: "[critical]",
}


def _load_report(path: Path) -> SystemReport:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"Diagnostic report not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON report: {path}: {exc}") from exc

    try:
        return SystemReport.model_validate(raw)
    except ValidationError as exc:
        raise SystemExit(f"Report does not match SystemReport schema:\n{exc}") from exc


def _render_plan(plan: InstallPlan) -> str:
    lines: list[str] = []

    lines.append("# Arch Btrfs AI Advisor")
    lines.append("")
    lines.append("## Summary")
    lines.append(plan.summary)
    lines.append("")

    if plan.assumptions:
        lines.append("## Assumptions")
        for assumption in plan.assumptions:
            lines.append(f"- {assumption}")
        lines.append("")

    if plan.warnings:
        lines.append("## Warnings")
        for warning in plan.warnings:
            lines.append(f"- {warning}")
        lines.append("")

    lines.append("## Steps")
    for index, step in enumerate(plan.steps, start=1):
        lines.append(f"{index}. {step.title}")
        lines.append(f"   {step.description}")
        if step.command is not None:
            icon = _RISK_ICON[step.command.risk]
            confirm = "requires confirmation" if step.command.requires_confirmation else "no confirmation required"
            lines.append(f"   - Command: `{step.command.command}`")
            lines.append(f"   - Risk: {icon} {step.command.risk.value} ({confirm})")
            lines.append(f"   - Reason: {step.command.reason}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Create a conservative Arch Btrfs installation plan from diagnostics JSON."
    )
    parser.add_argument(
        "report",
        type=Path,
        help="Path to diagnostics/system_report.json generated by scripts/diagnostics.sh.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the generated InstallPlan as JSON instead of Markdown.",
    )

    args = parser.parse_args(argv)

    report = _load_report(args.report)
    summary = summarize_hardware(report)
    plan = create_initial_plan(summary)

    if args.json:
        print(plan.model_dump_json(indent=2))
    else:
        print(_render_plan(plan), end="")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
