from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class CommandRisk(StrEnum):
    """Risk level for a command proposed by the installer advisor."""

    SAFE = "safe"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class SystemInfo(BaseModel):
    """Normalized system facts extracted from diagnostics/system_report.json."""

    boot_mode: str = Field(default="unknown", description="UEFI, BIOS or unknown")
    cpu_vendor: str = Field(default="unknown", description="CPU vendor from lscpu")
    network_link_up_detected: str = Field(default="unknown", description="yes, no or unknown")


class SystemReport(BaseModel):
    """Diagnostic report generated by scripts/diagnostics.sh."""

    schema_version: str
    generated_at_utc: str | None = None
    safety: dict[str, Any] = Field(default_factory=dict)
    system: SystemInfo = Field(default_factory=SystemInfo)
    commands: dict[str, str] = Field(default_factory=dict)
    ai_advisor_notes: dict[str, Any] = Field(default_factory=dict)


class InstallCommand(BaseModel):
    """A command proposed as part of an installation plan."""

    command: str
    risk: CommandRisk
    requires_confirmation: bool
    reason: str


class InstallStep(BaseModel):
    """Human-readable installation step with optional command."""

    title: str
    description: str
    command: InstallCommand | None = None


class InstallPlan(BaseModel):
    """Machine-readable installation plan for human review."""

    summary: str
    assumptions: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    steps: list[InstallStep] = Field(default_factory=list)
